### ISSUE TITLE
Recipe Management Backend

### ISSUE THREAD

**Issue by MBeuttler** [IUNO-TDM/JuiceMarketplaceWebsite#2]
Implement Backend interfaces and logic for:

- [ ] Create/add recipe
- [ ] Changed/edit recipe
- [ ] Delete recipe

**Comment by gomarcel** [comment]
Add also disable recipe. If a receipe is deleted, then all the recipe history is going to be deleted also. This may cause some problems with reporting and cash monitoring. More convenient is to "disable" the recipe, so that this is no longer active but all the history to that recipe is keeped on the database.
